### ISSUE TITLE
Content edit issue

### ISSUE THREAD

**Issue by jessicareed** [bppwrite/bppwrite.github.io#20]
My first issue! 

I need to edit the Guidelines for Submissions on the Woodward/Newman Drama page (http://newplays.org/submit-a-play/woodward-newman-drama/). 

However, in atom, this is what it looks like: 

![screen shot 2017-01-26 at 2 29 51 pm](https://cloud.githubusercontent.com/assets/8183594/22347378/c0a2d53e-e3d5-11e6-8f99-ca3f0c0c2ba5.png)
 
How can I edit the content that is in {{< submission_guidelines >}} - is this a link? A document?

**Comment by marcguyer** [comment]
Yeah, that's a little tricky. Since the guidelines are displayed on multiple pages, we created a reusable element that's behind the `{{< submission_guidelines >}}`. You'll find that in HTML in [layouts/shortcodes/submission_guidelines.html](https://github.com/bppwrite/bppwrite.github.io/blob/dev/layouts/shortcodes/submission_guidelines.html)
