### ISSUE TITLE
Changes I don't recognize?

### ISSUE THREAD

**Issue by jessicareed** [bppwrite/bppwrite.github.io#27]
I made one change to the show description on the Out of Orbit page and when I went to sync, there are 34 changes sitting there waiting for sync. I have no idea what they are - it appears that they are from when I created the 17-18 Season pages, which was a month ago. I know that I've made changes since then and it seems like these changes just appeared all of a sudden. All of the 17-18 season pages are up and running, etc. so I don't want to sync these. @marcguyer what should I do with this? 

![screen shot 2017-07-14 at 8 21 20 am](https://user-images.githubusercontent.com/8183594/28212143-045113dc-686e-11e7-817d-ec1dbaea2c2b.png)

**Comment by marcguyer** [comment]
Sync is bidirectional, so you could be simply receiving changes made by others since your last sync. @mattbatman and I have made changes since your last changed. What you're seeing could simply be those changes. Additionally, if you've made changes from a different device, you may be syncing changes to a new device. Just sync.

**Comment by jessicareed** [comment]
This is what I see now when I sync - I don't know what to do. How do I resolve these conflicts? 

![screen shot 2017-07-17 at 9 15 37 am](https://user-images.githubusercontent.com/8183594/28269636-c4ab08e0-6ad0-11e7-8879-582b7da64b10.png)

**Comment by marcguyer** [comment]
It's happening because we both modified the same files -- as I recall, I did the image optimizations for you, among other things. You'll need to learn how to resolve merge conflicts. I'm not familiar with how that's done with the UI you're using. I'll have to take a look directly at your environment to be able to help.

**Comment by jessicareed** [comment]
Can I commit and sync specific changes and ignore these for now or is it an all or nothing situation?

**Comment by marcguyer** [comment]
I'll have to take a look directly at your environment to be able to help.
