### ISSUE TITLE
Sponsor Logos added and deleted

### ISSUE THREAD

**Issue by jessicareed** [bppwrite/bppwrite.github.io#30]
23 hours ago I committed a change and synced, but I don't see the changes showing up on the live site. I see them when I look at the site locally, but I assume I've missed a step somewhere and I can't figure out where. @marcguyer, do you see where I've missed something?

**Comment by marcguyer** [comment]
You'll see the logos locally because the files exist locally. You don't see them on the site because the build failed. It failed because the sponsor content files have errors. You can see those errors in the terminal when you run `hugo serve`. The [frontmatter in the content files](https://github.com/bppwrite/bppwrite.github.io/blob/dev/CONTRIBUTING.md#set-the-frontmatter-for-the-content-file-1) (`[sponsor-name]/index.md`) needs to be completed. At least `date` and `title` (sponsor name) are required but you should fill out everything -- notably the website so the logos can be linked to the sponsor's website.
