### ISSUE TITLE
Nav Improvements

### ISSUE THREAD

**Issue by mattbatman** [bppwrite/bppwrite.github.io#4]
Here are some iterations on a new navigation.

![just-font](https://cloud.githubusercontent.com/assets/8661427/17827598/8108c042-664d-11e6-8157-05fdcdcb2e32.png)
![social-icons](https://cloud.githubusercontent.com/assets/8661427/17827599/8dc88b46-664d-11e6-85d9-9ca3227f8903.png)
![big-union](https://cloud.githubusercontent.com/assets/8661427/17827600/8e6adf2c-664d-11e6-8db0-11e284a096de.png)
![holy-heck](https://cloud.githubusercontent.com/assets/8661427/17827601/8f58e7ee-664d-11e6-9878-80bfaa2751ae.png)
![pratt](https://cloud.githubusercontent.com/assets/8661427/17827602/9442bf14-664d-11e6-8f14-7a545e1a71bf.png)
![hotel-esencia](https://cloud.githubusercontent.com/assets/8661427/17827603/96d5a55c-664d-11e6-9dcb-924daab50c1b.png)

**Comment by marcguyer** [comment]
I like them all

**Comment by marcguyer** [comment]
My favs are 2, 3, and 4. A streak of inspiration.

**Comment by marcguyer** [comment]
From Chad:

> Below are the pages and subpages I think we need.  Thinking more about the auto tracking of our artists and their bios, I think that would be very valuable for our playwrights, but not so necessary for our other artists.  Not to sound harsh, but most of our artists don’t have impressive resumes that would sell a ticket or convince someone who doesn’t know us that we’re a big deal, so I don’t know that it’s necessarily a good thing to have on our site.  But, on the other hand, keeping track of our alumni playwrights and their bios is valuable.  And it’s what we’re about.  So I’ve replaced “Submit a Play” with “Playwrights” where I’d love to track them.  Let me know if you have any questions or concerns.  Oh, and a blog thing could be added eventually.  I think it’s best to bury it in a sub-heading for now until we see if we can actually create the content.  Thanks!

> * Shows - Plays and events listed chronologically – like ATF’s site is fine – denoting which is a show and which is a special event
>     * Sub-pages for each show
> * Tickets
>     * Single Tickets
>     * Subscriptions
> * Calendar
> * Education (page and link for each of the following)
>     * BKids
>     * DCats
>     * Laugh Factory
>     * Musical
>     * After School Edventures
>     * MiniPlay
> * Playwrights
>     * Alumni Playwrights
>     * Submit a Play
>     * Reva Shiner Comedy
>     * Woodward/Newman Drama
> * Photo Gallery
> * Get Involved
>     * Volunteer
>     * Auditions
>     * Tech Opportunities
> * Support
>     * Individual
>     * Corporate
> * Facility Rentals
> * About Us
>     * Staff
>     * Board
>     * Directors Circle
>     * Mission & History
>     * Past Productions
>     * Arts Fair
>     * Contact Us

**Comment by marcguyer** [comment]
Based on my analysis of the current site's analytics, we can conclude the following:

1. It's all about the shows. The dramatic front-runner for unique pageviews is always the show that is currently running or is about to start. There is no contest. 
2. Again, shows. Ranking second in page views is the list of shows/events. 
3. "Submit a play" is a distant third place -- obviously a different audience.
4. Virtually everything else is useless compared to the first 3.

So, in short, approximately 3 out of 4 visitors are looking for info about shows: Probably trying to answer these and related questions: "what's that show again?" or "when does that show start?" or "how do I get tix to that show this weekend?" or "when are the other showtimes for that show?" 

I propose that we have a severely abbreviated main nav or consider removing the nav from the top of the home page altogether. Keep in mind that we can (and arguably should) always have a sitemap-style nav at the bottom so that when someone arrives at the site and they aren't looking for the top 3-4 things, they can find them easily at the bottom (as is customary for all that non-core info). 

If an abbreviated nav, I propose:

1. Shows (that's what the lion's share of visitors want)
2. Playwrights (that's the mission)
3. Support (that's what you want)

Anything else that's seasonal (Education, arts fair, etc) could be highlighted in a special hero during that timeframe. 

I'd be curious to see the ATF analytics to see if it corroborates my findings for the BPP site. @ChadDR can we have access to that? At least temporarily? Alternatively, the top 10-20 pages (by month, by unique pageview) would be mostly what we're interested in.

**Comment by ChadDR** [comment]
This is the ATF password to the google analytics:

 

 <mailto:atfeststats@gmail.com> atfeststats@gmail.com
Password: 61Street56

 

Chad Rabinovitz

Producing Artistic Director

Bloomington Playwrights Project

812-334-1188

 <mailto:artisticdirector@newplays.org> artisticdirector@newplays.org

 <http://www.newplays.org> www.newplays.org

**Comment by marcguyer** [comment]
Thanks for that. Confirmed my suspicions:

* ~25% homepage
* >50% shows (including looking for tickets ~18%)
* <2% submissions -- I think BPP has way more of this activity, correct?
* <2% photo gallery

@mattbatman let's get lunch tomorrow (or soon) to chat about some ideas.

**Comment by mattbatman** [comment]
@marcguyer Could we do Thursday or Friday?

**Comment by ChadDR** [comment]
Yeah, that sounds about right.  ATF isn’t known for play submissions.  And our site is sales driven.

 

Chad Rabinovitz

Producing Artistic Director

Bloomington Playwrights Project & Adirondack Theatre Festival

 <mailto:ChadDR@aol.com> ChadDR@aol.com

 <http://www.ChadDirects.com> www.ChadDirects.com

**Comment by marcguyer** [comment]
@mattbatman take a look at the [PromisePay index](https://promisepay.com/). That nav is something like what you were describing I think... It's exactly the same in mobile view.

**Comment by marcguyer** [comment]
@mattbatman I created a comprehensive menu in ee1bba18b14f02ac3294ad2a111edab43566102f to facilitate what we talked about the other day.
