### ISSUE TITLE
"Music & Lyrics" line on Tuning In show page

### ISSUE THREAD

**Issue by JSurigao** [bppwrite/bppwrite.github.io#43]
This is how I input Larry Kass for Music & Lyrics, following what was done for Front Page Flo from last season, and I just realized it didn't show up on the show page on the site. 

On the site, it should read "Music & Lyrics by Larry Kass"

Should this be done another way? 

![screen shot 2018-08-02 at 11 10 36 am](https://user-images.githubusercontent.com/33761733/43593101-02ed41fe-9645-11e8-9206-bcf9686021cf.png)
![screen shot 2018-08-02 at 11 10 54 am](https://user-images.githubusercontent.com/33761733/43593113-0886d83c-9645-11e8-8fca-1fbfe7488507.png)

**Comment by JSurigao** [comment]
This should also say "Directed & Choreographed by George Pinney"

The musical direction line doesn't even need to be there. I can take that line out (thought it's not showing up on the website anyway).

**Comment by marcguyer** [comment]
The byline display logic is quite complex when the `genres` frontmatter variable includes `musical` in the set. It's a bit esoteric but the code is here: 

https://github.com/bppwrite/bppwrite.github.io/blob/dev/layouts/partials/show_or_event/byline.html

The `genres` var was empty so I went ahead and added the `musical` genre to the set in 0061773d2d16ec198c2e3fc0ab3ed0944140e0fb. So, you can now [see the result on the live site](https://newplays.org/show/2018-2019/tuning-in/).

The choreographer value is ignored for the purposes of the byline. This is by design.
